# Generated by Django 4.2 on 2023-08-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=10)),
                ('siren', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('ebitda', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
